### PR TITLE
Delay initialization until rundeck has bootstrapped

### LINKED ISSUE #7: Early framework access breaking cluster message processing
Add-on appears to be accessing the framework service before Rundeck has bootstrapped and initialized it. This can cause, at least, the server UUID to never become populated and result in `NPE` during cluster message processing:

```
java.lang.NullPointerException: Cannot invoke method toUpperCase() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91) ~[groovy-2.5.6.jar:2.5.6]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:43) ~[groovy-2.5.6.jar:2.5.6]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.6.jar:2.5.6]
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34) ~[groovy-2.5.6.jar:2.5.6]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.6.jar:2.5.6]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:52) ~[groovy-2.5.6.jar:2.5.6]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-2.5.6.jar:2.5.6]
        at rundeckpro.services.HeartbeatService.findSiblingMembers(HeartbeatService.groovy:771) ~[rundeckpro-cluster-3.3.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]

```

### PR DESCRIPTION
**Pull request by ProTip**
Fixes #7

Potential fix for #7 . At the very end of the main application bootstrap it emits the `rundeck.bootstrap` event. This PR centralizes the init process and kicks off in response to the message.

Downside to this is the initialization is asynchronous. It may be inappropriate for the application to continue to load without this plugin having initialized.

### CODE REVIEW

**Review by gschueler — APPROVED** [review]

File: rundeck-execution-mode-timer/src/main/groovy/com/rundeck/plugin/EnableLaterExecutionsPluginGrailsPlugin.groovy [hunk 1]
```diff
@@ -5,6 +5,7 @@ import grails.plugins.*
 
 class EnableLaterExecutionsPluginGrailsPlugin extends Plugin {
 
+    def loadAfter = ['rundeckapp']
```
Comment (ProTip) [inline rundeck-execution-mode-timer/src/main/groovy/com/rundeck/plugin/EnableLaterExecutionsPluginGrailsPlugin.groovy]:
```suggestion
```
